---
- name: Implementing Global Scope Variables.
  hosts: all
  tasks: 
    - name: Create users
      user:
        name: "{{a}}"
        password: "{{b}}"
        home: "{{c}}"
    - name: Create files/dirs in users home dirs
      file:
        name: "{{d}}"
        state: "{{e}}"
...  

- 
