---
- name: Configuring Tomcat10
  hosts: all
  tasks: 
    - name: Install tomcat10
      apt:
        name: tomcat10
        state: present
        update_cache: yes
    - name: Install tomcat10-admin
      apt:  
        name: tomcat10-admin
        state: present
    - name: Copy tomcat-users.xml
      copy:
        src: tomcat-users.xml
        dest: /etc/tomcat10
    - name: Change port of Tomcat10 from 8080 to 9090
        replace:
        regexp: 8080
        replace: 9090
        path: /etc/tomcat10/server.xml
    - name: Restart tomcat10
      service:
        name: tomcat10
        state: restarted
    - name: Pause for 20 Seconds until Tomcat Server is Restarted
      pause:
        seconds: 20
    - name: Check tomcat on Server1
      uri:
        url: http://172.31.24.13:9090
        status_code: 200
    - name: Check tomcat on Server2
      uri:
        url: http://172.31.20.12:9090
        status_code: 200

...          
