---
- name: Configure Jenkins and required Software
  hosts: jenkinsServer
  become: yes
  tasks:
    - name: Install necessary Softwares
      apt:
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items: 
        - {a: openjdk-17-jdk,b: present,c: yes}
        - {a: git,b: present,c: no}
        - {a: maven,b: present,c: no}
    - name: Download Jenkins.war
      get_url:      
        url: https://get.jenkins.io/war-stable/2.504.1/jenkins.war
        dest: /home/ubuntu

- name: Configuring Tomcat on QA and PROD Servers
  hosts: webserver
  become: yes
  tasks:
    - name: Installing Tomcat10 and Tomcat10-admin
      apt:
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items:
        - {a: tomcat10,b: present,c: yes}
        - {a: tomcat10-admin,b: present,c: no}
    - name: Copy tomcat-users.xml file to all the servers
      copy: 
        src: /home/ubuntu/playbook/tomcat-users.xml
        dest: /etc/tomcat10
      notify: Restart tomcat
  handlers:
    - name: Restart tomcat
      service:
        name: tomcat10
        state: restarted   
...


