---
- name: Install and configure Tomcat10 on All the nodes
  hosts: all
  tasks:

  - name: Install Tomcat10 and Tomcat10-admin
    apt: 
      name: "{{item.a}}"
      state: "{{item.b}}"
      update_cache: "{{item.c}}"
    with_items:
      - {a: tomcat10,b: present, c: yes}
      - {a: tomcat10-admin,b: present,c: no}
  - name: Copy the tomcat-users.xml file 
    copy: 
      src: /home/ubuntu/playbook/tomcat-users.xml
      dest: /etc/tomcat10
  - name: Change port of tomcat10 from 8080 to 9091
    replace:
      regexp: 8080
      replace: 9091
      path: /etc/tomcat10/server.xml
  - name: Restart Tomcat10
    service: 
      name: tomcat10
      state: restarted
  - name: Pause for 30 seconds
    pause: 
      seconds: 30
  - name: Check tomcat status on Nodes.
    uri:
      url: "{{item}}"
      status_code: 200
    with_items: 
      - http://172.31.24.13:9091
      - http://172.31.20.12:9091
...        









