---
- name: Error Handling
  hosts: all
  tasks:
    - block:
      - name: Install Tree using apt module
        apt: 
          name: tree
          state: present
          update_cache: yes
      rescue:         
       - name: Install Tree using Yum Module
         yum:
           name: tree
           state: present
           update_cache: yes
...

