---
- name: Copy tomcat-users.xml file
  copy:
    src: "{{file1}}"
    dest: "{{dest1}}"
- name: Chacnge Port 8080 to 9090
  replace:
    regexp: "{{port1}}"
    replace: "{{port2}}"
    path: "{{path1}}"
  notify: check_url_response
...      
