#SPDX-License-Identifier: MIT-0
---
# tasks file for tomcat
- name: Call multiple child playbooks to install tomcat
  include_tasks: "{{item}}"
  with_items:
    - install.yml
    - configure.yml
    - restart.yml
...      
  
